replicaCount: 3 
image:
  repository: libremfg/packml-simulator
  pullPolicy: IfNotPresent

config:
  SITE: "Bathurst"
  AREA: "Packaging"
  LINE: "Line_1"
  MQTT_URL: "mqtt://emqx"
  MQTT_PORT: "1883"
  MQTT_USERNAME: "system"
  MQTT_PASSWORD: "public"
  TICK: 1000
  CLIENT_TYPE: "mqtt"